name = "my-worker"
type = "javascript"  # atau "webpack", "rust", "esm" tergantung build kamu
account_id = "kaykito"
workers_dev = true
compatibility_date = "2025-04-06"

[build]
command = "pnpm install && pnpm build"
